### PR TITLE
BROKERS: LoggingBroker - LogTrace

### LINKED ISSUE #28: BROKERS: LoggingBroker - LogTrace

### PR DESCRIPTION
**Pull request by SlimAhmad**
Closes #28

### CODE REVIEW

**Review by cjdutoit — COMMENTED** [review]
Looks good.  Please resolve the conflict on this PR, by bringing in the changes from main.

**Comment by glhays** [comment]
@SlimAhmad you need to sync your forks main with head main. Then merge main on this branch. The one logging broker was merged and your now in conflict without merging mains changes.

**Comment by SlimAhmad** [comment]
@glhays thanks Greg that helped a lot

**Review by cjdutoit — APPROVED** [review]
Looks good.  Please resolve the conflict on this PR, by bringing in the changes from main.

**Pull request merged**
