### PR TITLE
CONTROLLERS: Repository Controller - GetById

### LINKED ISSUE #232: CONTROLLERS: Repository Controller - GetById

### PR DESCRIPTION
**Pull request by SlimAhmad**
Closes #232

### CODE REVIEW

**Comment by glhays** [comment]
@SlimAhmad need to see an api test screenshot for these controllers

**Comment by SlimAhmad** [comment]
@glhays noted ,I wasn't done yet that's why I didn't request for a review i'll be putting them in tomorrow morning

**Comment by glhays** [comment]
Ok TY, you can mark the PR as draft to. Will keep prying eyes like mine away.  : )

**Comment by SlimAhmad** [comment]
image

**Review by cjdutoit — APPROVED** [review]

**Pull request merged**
